apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: noisy-unicorn-python
  janus-idp.io/tekton: noisy-unicorn-python
  backstage.io/kubernetes-id: noisy-unicorn-python
  backstage.io/kubernetes-namespace: rhtap-e2e-demo 
  app.kubernetes.io/part-of: noisy-unicorn-python
resources: 
- deployment.yaml
- route.yaml
- service.yaml
