apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: noisy-unicorn-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: noisy-unicorn-python 
  name: noisy-unicorn-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: noisy-unicorn-python 
